"""initial schema

Revision ID: 70c2fb9c3de9
Revises: 
Create Date: 2026-10-02 11:59:24.199489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c2fb9c3de9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alliances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=90), nullable=False),
    sa.Column('slug', sa.String(length=110), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('tagline', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('emblem', sa.String(length=8), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alliances'))
    )
    with op.batch_alter_table('alliances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alliances_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_alliances_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_alliances_starts_on'), ['starts_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_alliances_status'), ['status'], unique=False)

    op.create_table('donation_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('method', sa.String(length=60), nullable=False),
    sa.Column('account', sa.String(length=120), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=8), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donation_channels'))
    )
    op.create_table('donation_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('target', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donation_goals'))
    )
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_name', sa.String(length=80), nullable=False),
    sa.Column('message', sa.String(length=400), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('channel', sa.String(length=60), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('donated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donations'))
    )
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donations_donated_at'), ['donated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_is_public'), ['is_public'], unique=False)

    op.create_table('live_streams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=80), nullable=True),
    sa.Column('embed_url', sa.String(length=400), nullable=True),
    sa.Column('watch_url', sa.String(length=255), nullable=False),
    sa.Column('league', sa.String(length=80), nullable=True),
    sa.Column('competition', sa.String(length=80), nullable=True),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('viewers', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_live_streams'))
    )
    with op.batch_alter_table('live_streams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_streams_is_live'), ['is_live'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_streams_platform'), ['platform'], unique=False)

    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('haxball_url', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('players_online', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('map_name', sa.String(length=80), nullable=True),
    sa.Column('mode', sa.String(length=40), nullable=True),
    sa.Column('ping', sa.String(length=40), nullable=True),
    sa.Column('password', sa.String(length=60), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms')),
    sa.UniqueConstraint('code', name='uq_room_code')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_is_open'), ['is_open'], unique=False)

    op.create_table('rule_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=90), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_entries'))
    )
    with op.batch_alter_table('rule_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_entries_scope'), ['scope'], unique=False)

    op.create_table('sanction_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('items', sa.Text(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sanction_levels'))
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('year', sa.String(length=12), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('registration_opens', sa.Date(), nullable=True),
    sa.Column('is_registration_open', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seasons')),
    sa.UniqueConstraint('number', name='uq_season_number')
    )
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seasons_is_current'), ['is_current'], unique=False)

    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('group', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('input_type', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_settings'))
    )
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_settings_key'), ['key'], unique=True)

    op.create_table('social_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=24), nullable=False),
    sa.Column('owner', sa.String(length=24), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('handle', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=8), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_links'))
    )
    with op.batch_alter_table('social_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_links_is_primary'), ['is_primary'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_links_owner'), ['owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_links_platform'), ['platform'], unique=False)

    op.create_table('staff_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('bio', sa.String(length=400), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('banner', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.String(length=160), nullable=True),
    sa.Column('discord', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('is_leader', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_members'))
    )
    with op.batch_alter_table('staff_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_members_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_members_is_leader'), ['is_leader'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_members_role'), ['role'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=24), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('is_active_account', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=60), nullable=True),
    sa.Column('bio', sa.String(length=400), nullable=True),
    sa.Column('haxball_id', sa.String(length=40), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('google_email', sa.String(length=160), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role in ('admin','staff','user')", name=op.f('ck_users_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_logs'))
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_user_id'), ['user_id'], unique=False)

    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('short', sa.String(length=8), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('teams_count', sa.Integer(), nullable=False),
    sa.Column('journeys_count', sa.Integer(), nullable=False),
    sa.Column('playoffs_slots', sa.Integer(), nullable=False),
    sa.Column('relegation_slots', sa.Integer(), nullable=False),
    sa.Column('promotion_slots', sa.Integer(), nullable=False),
    sa.Column('modality', sa.String(length=60), nullable=True),
    sa.Column('duration', sa.String(length=80), nullable=True),
    sa.Column('map_name', sa.String(length=80), nullable=True),
    sa.Column('server', sa.String(length=60), nullable=True),
    sa.Column('tolerance', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schedule_note', sa.String(length=200), nullable=True),
    sa.Column('document_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_divisions_season_id_seasons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_divisions')),
    sa.UniqueConstraint('key', name=op.f('uq_divisions_key'))
    )
    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_divisions_season_id'), ['season_id'], unique=False)

    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(length=400), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('cover', sa.String(length=255), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('attachment', sa.String(length=255), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("category in ('general','inscripcion','premios','sanciones','eventos','sorteos','entrevista')", name=op.f('ck_articles_category_valid')),
    sa.CheckConstraint("kind in ('news','announcement','report')", name=op.f('ck_articles_kind_valid')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_articles_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], name=op.f('fk_articles_division_id_divisions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles'))
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index('ix_article_kind_published', ['kind', 'is_published', 'published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_is_featured'), ['is_featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_is_pinned'), ['is_pinned'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_slug'), ['slug'], unique=True)

    op.create_table('division_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], name=op.f('fk_division_rules_division_id_divisions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_division_rules'))
    )
    with op.batch_alter_table('division_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_division_rules_division_id'), ['division_id'], unique=False)

    op.create_table('phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('highlight', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], name=op.f('fk_phases_division_id_divisions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phases'))
    )
    with op.batch_alter_table('phases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phases_division_id'), ['division_id'], unique=False)

    op.create_table('promotion_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('tag', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('body', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], name=op.f('fk_promotion_slots_division_id_divisions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_slots'))
    )
    with op.batch_alter_table('promotion_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promotion_slots_division_id'), ['division_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('short', sa.String(length=20), nullable=False),
    sa.Column('slug', sa.String(length=90), nullable=False),
    sa.Column('crest', sa.String(length=255), nullable=True),
    sa.Column('coach', sa.String(length=60), nullable=True),
    sa.Column('captain', sa.String(length=60), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('founded_year', sa.String(length=12), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], name=op.f('fk_teams_division_id_divisions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('name', name=op.f('uq_teams_name'))
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_division_id'), ['division_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_slug'), ['slug'], unique=True)

    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('journey', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('played_on', sa.Date(), nullable=True),
    sa.Column('kickoff', sa.String(length=5), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('room_url', sa.String(length=255), nullable=True),
    sa.Column('replay_url', sa.String(length=255), nullable=True),
    sa.Column('stream_url', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status in ('scheduled','live','finished','wo','postponed')", name=op.f('ck_matches_status_valid')),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name=op.f('fk_matches_away_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], name=op.f('fk_matches_division_id_divisions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name=op.f('fk_matches_home_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches'))
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index('ix_match_division_journey', ['division_id', 'journey'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_away_team_id'), ['away_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_division_id'), ['division_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_home_team_id'), ['home_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_journey'), ['journey'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_played_on'), ['played_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_status'), ['status'], unique=False)

    op.create_table('museum_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('division_short', sa.String(length=8), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('recipient', sa.String(length=80), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('place', sa.Integer(), nullable=False),
    sa.Column('awarded_on', sa.Date(), nullable=True),
    sa.Column('is_highlight', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_museum_items_team_id_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_museum_items'))
    )
    with op.batch_alter_table('museum_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_museum_items_awarded_on'), ['awarded_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_museum_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_museum_items_slug'), ['slug'], unique=True)

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('haxball_id', sa.String(length=40), nullable=True),
    sa.Column('position', sa.String(length=24), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('is_captain', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('matches', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('clean_sheets', sa.Integer(), nullable=False),
    sa.Column('clean_sheet_seconds', sa.Integer(), nullable=False),
    sa.Column('own_goals', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_players_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_team_id'), ['team_id'], unique=False)

    op.create_table('standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('drawn', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], name=op.f('fk_standings_division_id_divisions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_standings_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standings')),
    sa.UniqueConstraint('division_id', 'team_id', name='uq_standing_division_team')
    )
    with op.batch_alter_table('standings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standings_division_id'), ['division_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_standings_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standings_team_id'))
        batch_op.drop_index(batch_op.f('ix_standings_division_id'))

    op.drop_table('standings')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_team_id'))
        batch_op.drop_index(batch_op.f('ix_players_is_active'))

    op.drop_table('players')
    with op.batch_alter_table('museum_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_museum_items_slug'))
        batch_op.drop_index(batch_op.f('ix_museum_items_category'))
        batch_op.drop_index(batch_op.f('ix_museum_items_awarded_on'))

    op.drop_table('museum_items')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_status'))
        batch_op.drop_index(batch_op.f('ix_matches_played_on'))
        batch_op.drop_index(batch_op.f('ix_matches_journey'))
        batch_op.drop_index(batch_op.f('ix_matches_home_team_id'))
        batch_op.drop_index(batch_op.f('ix_matches_division_id'))
        batch_op.drop_index(batch_op.f('ix_matches_away_team_id'))
        batch_op.drop_index('ix_match_division_journey')

    op.drop_table('matches')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_slug'))
        batch_op.drop_index(batch_op.f('ix_teams_is_active'))
        batch_op.drop_index(batch_op.f('ix_teams_division_id'))

    op.drop_table('teams')
    with op.batch_alter_table('promotion_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promotion_slots_division_id'))

    op.drop_table('promotion_slots')
    with op.batch_alter_table('phases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phases_division_id'))

    op.drop_table('phases')
    with op.batch_alter_table('division_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_division_rules_division_id'))

    op.drop_table('division_rules')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_slug'))
        batch_op.drop_index(batch_op.f('ix_articles_published_at'))
        batch_op.drop_index(batch_op.f('ix_articles_kind'))
        batch_op.drop_index(batch_op.f('ix_articles_is_published'))
        batch_op.drop_index(batch_op.f('ix_articles_is_pinned'))
        batch_op.drop_index(batch_op.f('ix_articles_is_featured'))
        batch_op.drop_index(batch_op.f('ix_articles_category'))
        batch_op.drop_index('ix_article_kind_published')

    op.drop_table('articles')
    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_divisions_season_id'))

    op.drop_table('divisions')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_action'))

    op.drop_table('activity_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('staff_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_members_role'))
        batch_op.drop_index(batch_op.f('ix_staff_members_is_leader'))
        batch_op.drop_index(batch_op.f('ix_staff_members_is_active'))

    op.drop_table('staff_members')
    with op.batch_alter_table('social_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_links_platform'))
        batch_op.drop_index(batch_op.f('ix_social_links_owner'))
        batch_op.drop_index(batch_op.f('ix_social_links_is_primary'))

    op.drop_table('social_links')
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_settings_key'))

    op.drop_table('site_settings')
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seasons_is_current'))

    op.drop_table('seasons')
    op.drop_table('sanction_levels')
    with op.batch_alter_table('rule_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_entries_scope'))

    op.drop_table('rule_entries')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_is_open'))

    op.drop_table('rooms')
    with op.batch_alter_table('live_streams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_streams_platform'))
        batch_op.drop_index(batch_op.f('ix_live_streams_is_live'))

    op.drop_table('live_streams')
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donations_is_public'))
        batch_op.drop_index(batch_op.f('ix_donations_donated_at'))

    op.drop_table('donations')
    op.drop_table('donation_goals')
    op.drop_table('donation_channels')
    with op.batch_alter_table('alliances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alliances_status'))
        batch_op.drop_index(batch_op.f('ix_alliances_starts_on'))
        batch_op.drop_index(batch_op.f('ix_alliances_slug'))
        batch_op.drop_index(batch_op.f('ix_alliances_kind'))

    op.drop_table('alliances')
    # ### end Alembic commands ###
